# Generated by Django 2.1.3 on 2018-12-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
