# Generated by Django 2.1.5 on 2019-01-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_funprofile'),
        ('competition', '0003_auto_20181207_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='base.Profile'),
            preserve_default=False,
        ),
    ]
