# Generated by Django 2.1.3 on 2018-11-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('config', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('next_sequence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Sequence')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=6)),
                ('number', models.PositiveIntegerField()),
                ('factor_value', models.DecimalField(decimal_places=3, max_digits=6)),
                ('angle', models.DecimalField(decimal_places=3, max_digits=6)),
                ('valid', models.BooleanField()),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Sequence')),
            ],
        ),
    ]
