# Generated by Django 2.1.3 on 2018-11-30 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisagProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Profile')),
                ('sch', models.CharField(choices=[('LG10', 'LG 10er-Band'), ('LG5', 'LG 5er-Band'), ('LGES', 'LG Einzelscheibe'), ('LP', 'LP'), ('ZS', 'Zimmerstutzen 15m'), ('LS1', 'Laufende Scheibe; ein Spiegel'), ('LS2', 'Laufende Scheibe; doppel Spiegel'), ('KK5', '50m Scheibe'), ('GK10', '100m - Scheibe für Groß und Kleinkaliber'), ('GK5', 'Kombischeibe 5-kreisig mit weißem Scheibenspiegel'), ('LPSF', 'LP Schnellfeuer'), ('SCHFE', 'Schnellfeuer- und Duell Scheibe.'), ('USE1', 'Benutzerdefiniert 1'), ('USE2', 'Benutzerdefiniert 2')], max_length=5, verbose_name='Scheibentype')),
                ('ria', models.CharField(choices=[('GR', 'Ganze Ringe'), ('ZR', 'Zehntel Ringe'), ('KR', 'Keine Ringe')], max_length=2, verbose_name='Ringauswertung')),
                ('kal', models.CharField(blank=True, choices=[('22', '22'), ('6MM', '6MM'), ('6.5MM', '6.5MM'), ('7MM', '7MM'), ('30', '30'), ('303', '303'), ('8MM', '8MM'), ('32', '32'), ('33', '33'), ('9MM', '9MM'), ('357', '357'), ('36', '36'), ('38', '38'), ('40', '40'), ('44', '44'), ('45', '45'), ('50', '50'), ('52', '52'), ('54', '54'), ('58', '58')], max_length=5, null=True, verbose_name='Kalibereinstellung')),
                ('rib', models.CharField(choices=[('RB', 'Ringberührungsmethode'), ('MI', 'Schußlochmittelpunkt für Vorderlader.')], max_length=2, verbose_name='Ringberechnung')),
                ('tea', models.CharField(choices=[('KT', 'Keine Teilerwertung'), ('ZT', 'Teilerwertung mit zehntel Teiler'), ('HT', 'Teilerwertung mit hundertstel Teiler')], max_length=2, verbose_name='Teilerauswertung')),
                ('teg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Teilergrenze')),
                ('ssc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Schußzahl pro Scheibe')),
                ('seg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Schußzahl Gesamt')),
                ('szi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Schußzahl pro Zwischensumme')),
                ('ksd', models.BooleanField(default=False, verbose_name='Kein Scheibenaufdruck')),
                ('tem', models.BooleanField(default=False, verbose_name='Teiler auf der Scheibe nur markieren')),
            ],
            bases=('base.profile',),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='config',
        ),
    ]
