# Generated by Django 2.1.3 on 2018-12-07 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20181130_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Profile')),
                ('seg', models.PositiveIntegerField(null=True, verbose_name='Schußzahl Gesamt')),
            ],
            bases=('base.profile',),
        ),
    ]
